name: Compile MiraiOK
on:
  push:
    branches:
      - master

jobs:
  my-job:
    name: Build MiraiOK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Golang environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.14.3' # The Go version to download (if necessary) and use.

      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}

      - name: Tidy Go modules
        run: go mod tidy

      - name: Windows x86
        run: GOOS=windows GOARCH=386 go build -ldflags "-w -s" -gcflags "-l=4" -o output/miraiOK_windows_386.exe .

      - name: Windows x64
        run: GOOS=windows GOARCH=amd64 go build -ldflags "-w -s" -gcflags "-l=4" -o output/miraiOK_windows_amd64.exe .

      - name: Linux amd64
        run: GOOS=linux GOARCH=amd64 go build -ldflags "-w -s" -gcflags "-l=4" -o output/miraiOK_linux_amd64 .

      - name: Linux arm64
        run: GOOS=linux GOARCH=arm64 go build -ldflags "-w -s" -gcflags "-l=4" -o output/miraiOK_linux_arm64 .

      - name: Linux arm
        run: GOOS=linux GOARCH=arm go build -ldflags "-w -s" -gcflags "-l=4" -o output/miraiOK_linux_arm .

      - name: Darwin amd64
        run: GOOS=darwin GOARCH=amd64 go build -ldflags "-w -s" -gcflags "-l=4" -o output/miraiOK_darwin_amd64 .

      - name: UPX
        uses: gacts/upx@master
        with:
          file: 'output/*'
          upx_args: '-9'

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: # optional
          # A file, directory or wildcard pattern that describes what to upload
          path: "output/"

